[package]
name = "rrdt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rrdt-lib = { "path" = "../rrdt-lib" }
tokio = { version = "1.34.0", features = ["full"] }
anyhow = "1.0.75"
futures = "0.3.30"
actix-rt = "2.9.0"
clap = { version = "4.4.8", features = ["derive"] }
